### PR TITLE
New Options

### PR DESCRIPTION
**Pull request by SlyFoxHayes**
I added 3 new options, each in their own branch in the repository.

- Branch **ConfigOptionLocalTime**: Adds optoin _ExceptionDateKind_ allowing you to specify whether you want the datetime of the exception reported in UTC or Local time.  Defaults to UTC.
- Branch **GetPublishedVersionIfNetworkDeployed**: Checks to see if this is a ClickOnce application, and retrieves the published version.
- Branch **SmtpClientImprovemets**: Adds option _UseDefaultCredentials_, allowing an email to be sent with the credentials of the logged in user.  This also defaults the SmtpPort to 25 if not specified.

The master branch is just the merger of the 3 branches.

### CODE REVIEW

**Comment by PandaWood** [comment]
Thanks, I just pushed up some new stuff, so I'll sort out this conflict and see what I can do

**Comment by PandaWood** [comment]
Thanks, all great changes. I just edited a spelling or something here or there but it's all in.

**Comment by SlyFoxHayes** [comment]
Awesome! Thanks. This is my first open source contribution. Is there anything else that needs to be changed documentation-wise?

**Comment by PandaWood** [comment]
I think we're good for doco...
- The configuration is only self-documented (using the summary XML in the code) so that's basically done
- And I will take care of describing the changes in the next release

BTW you can "star" the project as well as "follow" it ;-) 
I noticed we bumped up and down during this change.

**Comment by SlyFoxHayes** [comment]
It’s starred now. I got a little confused by that. To me, if I’m watching it, it should be automatically starred.

**Pull request merged**
