### PR TITLE
Mail priority

### PR DESCRIPTION
**Pull request by SlyFoxHayes**
This adds a config property called EmailPriority.  Used by Smtp.  I didn't see a priority property in SimpleMAPI.

This also adds a NuGet package "NUnit3TestAdapter".   I need this adapter to run the unit tests.  I am using VS2017 with MSTest V2.  I tried setting this up as a 2nd branch, but it slipped into this branch (MailPriority) by mistake.

### CODE REVIEW

**Comment by PandaWood** [comment]
Thanks

- I'm not exactly sure what the change to the project GUID of the web service means: in 'cwv'
`Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "WebService.ExceptionReporter"`
I might overrule that change and I think it should be OK

- The dependency on NUnitTestAdapter is no problem - it's in the test assembly (Tests.ExceptionReporter) - so it can have whatever it wants without affecting the release

- There slightly inconsistent whitespace in one of the changes but I'm happy to pull it in and fix that.

**Comment by PandaWood** [comment]
BTW in the very latest master commits, I've just started moving all the files that users need to use, out of ExceptionReporting.Core namespace/folder and into the root - so they only need to include one namespace using statement.

So looks like you just edited the old `ExceptionReporterInfo.cs`

PS the above change should not be a breaker for anyone, possibly except those who used the ExceptionReportGenerator class on it's own - I'll check that and if true, I will use semver principles and move to 3.0 for next release

**Comment by PandaWood** [comment]
Doh, no ignore my worrying about wrong file being edited, it's all good.

**Comment by PandaWood** [comment]
I just decided to change the property name to `SmtpMailPriority` - since all the SMTP-specific settings start with that.

**Comment by PandaWood** [comment]
BTW also it would be better to squash all your commits before submitting the PR.
I can't squash them without removing you from the commit log - which wouldn't seem fair ;-)

**Comment by SlyFoxHayes** [comment]
I don’t know why that guid changed either with the “cwv” commit.  It can be ignored.

Regarding the rename, I wasn’t viewing this as an Smtp only property, more of a property about the mail message being sent.
I know with MAPI, you can also specify a mail priority. It didn’t appear that SimpleMAPI exposed it, or I would have added for that mail method as well.
I was trying to make it mail method agnostic.

<removed email trail>

**Comment by PoLaKoSz** [comment]
> - I'm not exactly sure what the change to the project GUID of the web service means: in 'cwv'
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "WebService.ExceptionReporter"
I might overrule that change and I think it should be OK

This happend with me when I opened the solution for the first time.
@SlyFoxHayes do You have this error too?
>The current .NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 2.0 or lower, or use a version of the .NET SDK that supports .NET Core 2.1.	WebService.ExceptionReporter	C:\Program Files\dotnet\sdk\2.1.202\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	135	

<removed email fragment>

**Comment by SlyFoxHayes** [comment]
I do get that error now that you ask.
I didn’t get it previously, as I had disabled that project for building, as I’m not working with it presently.

<removed email trail>

**Comment by SlyFoxHayes** [comment]
Ok, makes sense.

<edited to remove email trail>

**Comment by PandaWood** [comment]
Looks like this error https://github.com/dotnet/cli/issues/8743
Which looks like a Visual Studio/.NET update complication - seems it might be a temporary bug caused maybe because I have the latest VS update installed and someone else doesn't.

**Pull request merged**
